version: '3'
services:
  app:
    environment:
      DEVCYCLE_SDK_KEY: "xxx"
    container_name: "DevCycleHTTPProxyWithNginxAndPhp82"
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
