version: '3'
services:
  app:
    container_name: "DevCycleUDPProxyWithNginxAndPhp82"
    build:
      context: .
      args:
        DEVCYCLE_SDK_KEY: "dvc_server_ef37f82e_a697_49f7_a78c_52b0350c5a38_9adcfa8"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
