version: '3'
services:
  app:
    environment:
      DEVCYCLE_SDK_KEY: "replace_with_your_sdk_key"
    container_name: "DevCycleUDPProxyWithNginxAndPhp82"
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
