# This is a basic workflow to help you get started with Actions

name: Packagist Notify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packagist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Action
        uses: joelwmale/webhook-action@2.3.2
        with:
          # The url to send the webhook event to
          url: https://packagist.org/api/github?username=DevCycle&apiToken=${{secrets.packagistToken}}
          # Additional headers to send alongside the defaults
          headers: '{"Content-Type": "application/json"}'
          body: '{"repository": {"url": "https://github.com/DevCycleHQ/php-server-sdk"}}'
            
